// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIB2peuUIUf3t7wkQpOunUpIpxgPQcoA8',
    appId: '1:977209493574:web:1462e6b13d7c487ec26247',
    messagingSenderId: '977209493574',
    projectId: 'mymapp-1556031423958',
    authDomain: 'mymapp-1556031423958.firebaseapp.com',
    storageBucket: 'mymapp-1556031423958.appspot.com',
    measurementId: 'G-V5N4BY4P7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_Sa9t_3ZE1URPbcVEYJBNsBgUXZSr_FA',
    appId: '1:977209493574:android:feb19fd06b477743c26247',
    messagingSenderId: '977209493574',
    projectId: 'mymapp-1556031423958',
    storageBucket: 'mymapp-1556031423958.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0E_rgb_JCGqT1uY3B9EP0EwHR9FkNtnc',
    appId: '1:977209493574:ios:d67d076c6a34e6cdc26247',
    messagingSenderId: '977209493574',
    projectId: 'mymapp-1556031423958',
    storageBucket: 'mymapp-1556031423958.appspot.com',
    iosBundleId: 'com.example.sygConducteur',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0E_rgb_JCGqT1uY3B9EP0EwHR9FkNtnc',
    appId: '1:977209493574:ios:5a91513b65d1cab3c26247',
    messagingSenderId: '977209493574',
    projectId: 'mymapp-1556031423958',
    storageBucket: 'mymapp-1556031423958.appspot.com',
    iosBundleId: 'com.example.sygConducteur.RunnerTests',
  );
}
